(() => {
  const tracks = {
    wrestling:{title:'Wrestling practice',name:'Competition Prep — Week 1',rows:[['Warm-up + movement','15'],['Technique: single-leg chain','25'],['Live goes: score first','30'],['Cool down + review','20']]},
    lifting:{title:'Lifting & conditioning',name:'Strength Cycle — Day 1',rows:[['Dynamic warm-up','10'],['Lower-body strength','30'],['Power + med ball','20'],['Mobility / recovery','15']]},
    mental:{title:'Mind & focus session',name:'Competition Mindset — Day 1',rows:[['Breathing reset','5'],['Visualization: first score','10'],['Decision game','20'],['Journal + cue words','10']]}
  };
  let track='wrestling'; let state=JSON.parse(localStorage.getItem('tp_draft')||'null')||{name:tracks.wrestling.name,date:'',minutes:90,rows:tracks.wrestling.rows};
  const $=id=>document.getElementById(id); const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
  function render(){const cfg=tracks[track];$('trackTitle').textContent=cfg.title;$('planName').value=state.name;$('planDate').value=state.date;$('totalMinutes').value=state.minutes;$('rows').innerHTML=state.rows.map((r,i)=>`<div class="row"><label>Activity<input data-i="${i}" data-k="0" value="${escapeHtml(r[0])}"></label><label>Min<input type="number" min="0" data-i="${i}" data-k="1" value="${escapeHtml(r[1])}"></label><button class="remove" data-remove="${i}" aria-label="Remove activity">×</button></div>`).join(''); updateProgress(); renderTemplates()}
  const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function updateProgress(){const used=state.rows.reduce((n,r)=>n+(Number(r[1])||0),0), total=Number(state.minutes)||0;$('timeLabel').textContent=`${used} / ${total} min`;$('timeBar').style.width=`${total?Math.min(100,used/total*100):0}%`}
  function save(){state={name:$('planName').value.trim()||'Untitled plan',date:$('planDate').value,minutes:Number($('totalMinutes').value)||0,rows:state.rows};localStorage.setItem('tp_draft',JSON.stringify(state));const list=JSON.parse(localStorage.getItem('tp_templates')||'[]');localStorage.setItem('tp_templates',JSON.stringify([state,...list.filter(x=>x.name!==state.name)].slice(0,8)));$('savedState').textContent='Saved locally';renderTemplates();toast('Plan saved')}
  function renderTemplates(){const list=JSON.parse(localStorage.getItem('tp_templates')||'[]');$('templates').innerHTML=list.length?list.slice(0,4).map((x,i)=>`<div class="template"><span>${escapeHtml(x.name)}</span><button data-load="${i}">Open</button></div>`).join(''):'<p class="small">Your saved plans will appear here.</p>';window._templates=list}
  $('rows').addEventListener('input',e=>{const i=e.target.dataset.i;if(i===undefined)return;state.rows[i][e.target.dataset.k]=e.target.value;updateProgress()});$('rows').addEventListener('click',e=>{const i=e.target.dataset.remove;if(i!==undefined){state.rows.splice(Number(i),1);render()}});
  document.querySelectorAll('.track').forEach(b=>b.addEventListener('click',()=>{track=b.dataset.track;document.querySelectorAll('.track').forEach(x=>x.classList.toggle('active',x===b));state={...state,name:tracks[track].name,rows:tracks[track].rows.map(x=>[...x])};render()}));
  $('addRow').onclick=()=>{state.rows.push(['New activity','10']);render();$('rows input').focus()};$('saveBtn').onclick=save;$('assignBtn').onclick=()=>toast('Assignment flow ready for Firebase connection');$('shareBtn').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Planner link copied')}catch{toast('Copy unavailable on this device')}};$('newBtn').onclick=()=>{state={...state,name:'New training plan',rows:[['Warm-up','10']]};render()};$('templates').onclick=e=>{const i=e.target.dataset.load;if(i!==undefined){state=JSON.parse(JSON.stringify(window._templates[i]));render();toast('Template opened')}};['planName','planDate','totalMinutes'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='planName')state.name=$(id).value;if(id==='planDate')state.date=$(id).value;if(id==='totalMinutes')state.minutes=Number($(id).value)||0;updateProgress()}));
  window.TP={save,tracks}; render();
})();